org:
    dromara:
        hmily:
            hmilyDbConfig:
                driverClassName: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://127.0.0.1:3316/tcc?serverTimezone=GMT%2B8
                username: "root"
                password: "1234qwer"

server:
    port: 8082